### ISSUE TITLE
Allocating RAM to minecraft

### ISSUE THREAD

**Issue by Xiaminou** [Watchful1/CurseAppFeatureTracker#10]
I should be able to allocate more than half my RAM to minecraft without having to put it as a parameter.
Oh and delete that awful "recommended" setting, it largely varies on modpacks, so there is no recommended.

**Comment by Watchful1** [comment]
Personally I actually disagree with this. Unless you're using a high resolution texture pack, using more than 3 gigs of ram is almost always counterproductive. Vazkii has a long post about it [here](http://vazkii.us/uncategorized/a-semi-technical-explanation-of-why-you-shouldnt-allocate-too-much-ram-to-minecraft/). And I think it's a good idea, at least on the surface, for curse to limit users from bad experiences by preventing them from allocating too much.

I'm not really sure how it performs in low ram environments, but if you have, say, 4 gigs of ram total, you probably don't want to be allocating more than 2 to minecraft anyway.

**Comment by SynfulChaot** [comment]
I understand their desire to save users from themselves, but not all of us users can't tell the difference between a CD-ROM drive and a cup holder.

Perhaps allow more power over the RAM settings and Java parameters after enabling an 'advanced mode' like many applications have?

**Comment by Watchful1** [comment]
Can you overwrite it with the java arguments box?

**Comment by Xiaminou** [comment]
I have read the post by Vazkii and all it says is "allocating too much ram is bad". Meanwhile I have ran out of ram with 6GB (my computer has 12) while exploring the overworld in my modpack. So I had to add the java argument myself.
But I don't see what that has to do with forcibly limiting users to an arbitrarily determined amount of RAM (why half?).
Yes you can overwrite it but my point is, why limit users? Is your opinion of the average user that bad?

**Comment by SynfulChaot** [comment]
To be fair, the average user _is_ that bad, but I don't think that making it _that_ difficult for us advanced users is a good option.  I'd still push for that 'advanced mode' thing.
