### ISSUE TITLE
Ability to downgrade mods

### ISSUE THREAD

**Issue by Xiaminou** [Watchful1/CurseAppFeatureTracker#4]
You can update mods but you cannot downgrade them, for that you have to delete the mod and then browse mods to install an older version.
If like myself you're updating mod daily you've most likely run into crash or game breaking bugs that need you to re-install the previous version of the mod.
When browsing the mod you should be able to click any version of the mod like you would for updating it.

**Comment by SynfulChaot** [comment]
I'd expand that to be able to upgrade or downgrade to any specific version directly.

**Comment by Xiaminou** [comment]
That's what I meant, any version. Sorry if you though it was only to the previous one.

**Comment by Watchful1** [comment]
This is already possible. In the installed mods list, click on the mod name, then versions, then click the download button next to the version you want.

**Comment by Xiaminou** [comment]
Hum, must have been added very recently because it didn't work last time I checked.
