### ISSUE TITLE
Forge auto-update

### ISSUE THREAD

**Issue by Xiaminou** [Watchful1/CurseAppFeatureTracker#5]
Let me open up by asking you one simple question, is there any reason to not use the latest forge available?
If the answer is no then I recommend adding an option to keep forge automatically updated to the latest recommended version of forge.

**Comment by Prospector** [comment]
I don't think this is a very good idea, forge is known for removing shit without deprecation

**Comment by Xiaminou** [comment]
Is it? because I've never had any trouble with recommended versions of forge.

**Comment by Watchful1** [comment]
There are numerous reasons not to want to update to the latest forge. Mods not being compatible with the latest version is the big one. Doing it automatically would likely annoy a lot of pack authors, especially since it's so easy to do it manually if you want to.

**Comment by Xiaminou** [comment]
I meant that for custom modpacks, not Curse or FTB packs.

**Comment by Watchful1** [comment]
Still. I wouldn't want curse to do something automatically that breaks the pack I'm playing.

**Comment by Xiaminou** [comment]
It wouldn't be for everyone, I agree. But I still think there should be an option for it, I certainly would use it.
