### ISSUE TITLE
Deleting a mod should not delete optional dependencies

### ISSUE THREAD

**Issue by Xiaminou** [Watchful1/CurseAppFeatureTracker#8]
I recently deleted EnderIO addons and it had fastcraft as an optional library, it deleted fastcraft too.

**Comment by DrasticDemise** [comment]
It should prompt for each dependency on if it should be deleted as well. There is no need for the library if the only mod that uses it has been removed, but it should atleast ask for each mod so something like this doesn't occur.

**Comment by SynfulChaot** [comment]
Perhaps instead of automatically removing, it can point out what mods are required and optional libraries of a mod when you remove it?

**Comment by SynfulChaot** [comment]
It should prompt regardless, even if no other mod is using a particular dependency, because some of those mods have features of their own that people may desire.

**Comment by Xiaminou** [comment]
it should prompt for deleting a mod too, just in case you missclick.

**Comment by SynfulChaot** [comment]
True.  An 'are you sure' isn't a bad idea for mod deletion.
