### ISSUE TITLE
Bug reports in the curse app give no feedback to the user

### ISSUE THREAD

**Issue by Xiaminou** [Watchful1/CurseAppFeatureTracker#9]
I know the readme says it's not the place to do that, and the bug report on Curse Voice app is the right way, but I'm gonna be honest, I hate that kind of bug report.
You have no idea if anyone's even seen your bug report, no idea if it's being worked on, nobody can talk about work-around, not to mention the tons of duplicate there must be.
Please use github, it's much better than what you're using.

**Comment by Watchful1** [comment]
I'll stress that this is not an official tracker. No curse employees are checking it regularly, there's no guarantee anything here will be implemented or fixed. This is so we, the members of the community can talk about things we want in the app.

I personally know a number of curse employees and hope to bring their attention to specific issues as people show support for them. But it's a manual process and wouldn't be suited to the number of minor, legitimate bugs that crop up.

More importantly, submitting through the app includes a number of comprehensive logs that are often crucial to the developers being able to resolve them. Simply explaining your bug often isn't enough.

However, you do bring up a good point. There's no feedback on bug reports. I'll edit your title a bit.

**Comment by Xiaminou** [comment]
So what happened to this, uh? I have reported multiple bugs to Curse, not only did none of them get fixed but I also got no feedback from them.
And apparently you're (collective) even ignoring mod authors, on whose backs Curse make all their money. Nice.

https://github.com/raoulvdberge/refinedstorage/issues/869

**Comment by Watchful1** [comment]
Literally nothing I can do mate. Try complaining to curse on twitter.
